import swaggerJsdoc from 'swagger-jsdoc';

const host = process.env.API_URL;

const options = {
  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
      title: 'Test API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
    },
    host, // Host (optional)
    schemes:
      - "http",
    basePath: '/',// Base path (optional)
    consumes:
      - "application/json; charset=utf-8",
    produces:
      - "application/json; charset=utf-8"
  },
  apis: ['./src/routes/*.js']
};

const SwaggerSpecs = swaggerJsdoc(options);

export default SwaggerSpecs
